services:
  # --------------------------------------------------------------------------------
  # APP: n8n
  # --------------------------------------------------------------------------------
  n8n:
    build:
      context: .
      dockerfile: n8n.Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "8080:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:8080/
      - GENERIC_TIMEZONE=America/New_York
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./content_factory:/files
    extra_hosts:
      - "host.docker.internal:host-gateway"
